server:
  port: 5467
name:
    prod
eureka:
    instance:
      hostname: localhost
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      server-url:
        defaultZone: http://localhost:8761/eureka

